
service: serverlessbot

provider:
  name: aws
  runtime: python3.6


functions:
  retweet:
    handler: handler.retweet
    events:
      - schedule: rate(2 hours)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
